# Generated by Django 4.1.6 on 2023-02-22 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import tmapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=80, verbose_name='Проект')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='Ключ')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_title', models.CharField(max_length=80, verbose_name='Спринт')),
                ('target', models.CharField(max_length=200, verbose_name='Цель спринта')),
                ('duration', models.CharField(choices=[('1W', '1 неделя'), ('2W', '2 недели'), ('3W', '3 недели'), ('4W', '4 недели')], max_length=8, verbose_name='Длительность')),
                ('sprint_start', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 32, 52, 595756), verbose_name='Дата начала')),
                ('sprint_end', models.DateTimeField(default=None, verbose_name='Дата окончания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmapp.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_title', models.CharField(max_length=200, unique=True)),
                ('weight', models.IntegerField()),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_title', models.CharField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='StatusAdmin',
            fields=[
                ('status_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tmapp.status')),
            ],
            bases=('tmapp.status',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyid', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=160, verbose_name='Задача')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('task_start', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 32, 52, 597543), verbose_name='Дата создания')),
                ('task_update', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 32, 52, 597565), verbose_name='Дата обновления')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmapp.project', verbose_name='Проект')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='tmapp.sprint', verbose_name='Спринт')),
                ('state', models.ForeignKey(default=tmapp.models.get_default_task_status, on_delete=django.db.models.deletion.PROTECT, to='tmapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('keyid', models.CharField(db_index=True, editable=False, max_length=20)),
                ('subject', models.CharField(max_length=160, verbose_name='Задача')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('task_start', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 32, 52, 597543), verbose_name='Дата создания')),
                ('task_update', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 32, 52, 597565), verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.project', verbose_name='Проект')),
                ('sprint', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.sprint', verbose_name='Спринт')),
                ('state', models.ForeignKey(blank=True, db_constraint=False, default=tmapp.models.get_default_task_status, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.state')),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state_title', models.CharField(db_index=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.status')),
            ],
            options={
                'verbose_name': 'historical status',
                'verbose_name_plural': 'historical statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalState',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state_title', models.CharField(db_index=True, max_length=200)),
                ('weight', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical state',
                'verbose_name_plural': 'historical states',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSprint',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sprint_title', models.CharField(max_length=80, verbose_name='Спринт')),
                ('target', models.CharField(max_length=200, verbose_name='Цель спринта')),
                ('duration', models.CharField(choices=[('1W', '1 неделя'), ('2W', '2 недели'), ('3W', '3 недели'), ('4W', '4 недели')], max_length=8, verbose_name='Длительность')),
                ('sprint_start', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 13, 32, 52, 595756), verbose_name='Дата начала')),
                ('sprint_end', models.DateTimeField(default=None, verbose_name='Дата окончания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tmapp.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'historical sprint',
                'verbose_name_plural': 'historical sprints',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_title', models.CharField(max_length=80, verbose_name='Проект')),
                ('key', models.CharField(db_index=True, max_length=10, verbose_name='Ключ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
