# Generated by Django 4.1.7 on 2023-03-18 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tmapp", "0002_add_default_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="project_start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 632328),
                verbose_name="Дата начала",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsprint",
            name="sprint_start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 634321),
                verbose_name="Дата начала",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="task_start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 637312),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="task_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 637312),
                verbose_name="Дата обновления",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 632328),
                verbose_name="Дата начала",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="sprint_start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 634321),
                verbose_name="Дата начала",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 637312),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_update",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 18, 20, 3, 57, 637312),
                verbose_name="Дата обновления",
            ),
        ),
    ]
