# Generated by Django 4.1.6 on 2023-03-03 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0002_add_default_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsprint',
            name='sprint_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 40, 35, 213789), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 40, 35, 215250), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 40, 35, 215265), verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 40, 35, 213789), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 40, 35, 215250), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 40, 35, 215265), verbose_name='Дата обновления'),
        ),
    ]
