# Generated by Django 4.1.6 on 2023-02-27 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmapp', '0002_add_default_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsprint',
            name='sprint_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 15, 19, 31, 268488), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 15, 19, 31, 269808), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 15, 19, 31, 269826), verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 15, 19, 31, 268488), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 15, 19, 31, 269808), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 15, 19, 31, 269826), verbose_name='Дата обновления'),
        ),
    ]
