# Generated by Django 4.1.6 on 2023-02-28 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmapp', '0003_alter_historicalsprint_sprint_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsprint',
            name='sprint_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 12, 37, 59, 535080), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 12, 37, 59, 536407), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='task_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 12, 37, 59, 536425), verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 12, 37, 59, 535080), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executors', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 12, 37, 59, 536407), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 12, 37, 59, 536425), verbose_name='Дата обновления'),
        ),
    ]
